# -*- coding: utf-8 -*-
"""phase2 project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13QwmON7HKuFq7pcPI43whQTlZ-nVmnQb
"""

import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer

# Download required NLTK data if not already downloaded
try:
    nltk.data.find('sentiment/vader_lexicon.zip')
except LookupError:
    nltk.download('vader_lexicon')

# Load the VADER sentiment analysis model
vader = SentimentIntensityAnalyzer()

# Sample text
text = "This is a great product! I love it."

# Analyze the sentiment
sentiment_scores = vader.polarity_scores(text)

# Print the results
print(f"Sentiment scores: {sentiment_scores}")
#  {'neg': 0.0, 'neu': 0.293, 'pos': 0.707, 'compound': 0.8402}

if sentiment_scores['compound'] >= 0.05:
    print("Positive sentiment")
elif sentiment_scores['compound'] <= -0.05:
    print("Negative sentiment")
else:
    print("Neutral sentiment")
#  Positive sentiment